# Generated by Django 5.2.6 on 2025-09-23 08:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_commissions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_payments', models.DecimalField(decimal_places=2, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('nrc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_bag', models.DecimalField(decimal_places=2, default=1200.0, max_digits=10)),
                ('commission_per_bag', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UCFPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment_type', models.CharField(choices=[('payment', 'Payment to UCF'), ('receipt', 'Receipt from UCF')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('reference_number', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DailySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bags_sold', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_earned', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizer_tracking.depot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizer_tracking.product')),
            ],
            options={
                'unique_together': {('date', 'depot', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizer_tracking.depot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizer_tracking.product')),
            ],
            options={
                'unique_together': {('depot', 'product')},
            },
        ),
    ]
