# Generated by Django 5.2.6 on 2025-09-23 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizer_tracking', '0002_alter_dailybalance_closing_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysale',
            name='depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fertilizer_tracking.depot'),
        ),
        migrations.AlterField(
            model_name='dailysale',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fertilizer_tracking.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fertilizer_tracking.depot'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fertilizer_tracking.product'),
        ),
    ]
