# Generated by Django 5.2 on 2025-09-28 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizer_tracking', '0003_alter_dailysale_depot_alter_dailysale_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('previous_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_type', models.CharField(choices=[('addition', 'Stock Addition'), ('sale', 'Stock Sale'), ('adjustment', 'Stock Adjustment'), ('correction', 'Stock Correction')], max_length=20)),
                ('bags_sold', models.IntegerField(blank=True, null=True)),
                ('quantity_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='fertilizer_tracking.stock')),
            ],
            options={
                'verbose_name_plural': 'Stock Histories',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
